server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dwlsxj/spring-cloud-test/tree/master/git-repo
          username: dwlsxj@126.com
          password: dwl08181217@sxj