server:
  port: 8889

eureka:
  instance:
    hostname: springclouduser
    prefer-ip-address: true
  #    metadata-map:
  #      user.name: ${security.user.name}
  #      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://admin:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/
    healthcheck:
      enabled: true

# Hystrix超时时间。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  zipkin:
    base-url: http://localhost:9411
