server:
  port: 8889

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://admin:${REGISTRY_SERVER_PASSWORD:password}@${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true

# Hystrix超时时间。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost

# Spring Boot Admin配置相关
# SpringBoot 1.5以后的版本都默认开启端点保护
management:
  security:
    enabled: false

