server:
  port: 8031
spring:
  application:
    name: springhystrixturbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: spring-cloud-user,spring-cloud-service
  clusterNameExpression: "'default'"