server:
  port: 8761  # 端口号

eureka:
  instance:
    hostname: springcloudeurekaserver
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
#      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka/
security:
  user:
    name: admin
    password: ${REGISTRY_SERVER_PASSWORD:password}